### ISSUE TITLE
Feature request -- custom URL instead of folder

### ISSUE THREAD

**Issue by benfletcher** [username0x0a/Tamperish#2]
Would it be possible to specify a URL instead of a local folder? For example, if I could specify a public Github repo or ghpages URL that has the same hierarchy as the local folder option, I could then share my customizations across installations without any server hierarchy needed on your part.

There would be noticeable lag and that would be the tradeoff required of users.

Hopefully Apple's strict policies on extensions would allow for this functionality, but could see that being an issue.

Naturally, I could simply clone this repo locally and make a script to pull/push changes from time to time. And that's what I'll in the mean time, but thank you for considering this feature!

Awesome work on this. Thanks for making it and making it work so flawlessly.

**Comment by username0x0a** [comment]
Hi, Ben!

I gave this idea a thought or two and to some extend, it would be doable, but with some implementation limitations of course.

- Network lagging – agreed, at least for the initial load as the Tampers structure could be (very preferably) cached, although that brings another factor of invalidation and refreshing. Not impossible to balance to some extend of usability, but definitely not an easy task. 😅
- Compliance with Apple's policies – not really a concern I'd be afraid of here, basically the local storage would need to be stored in application's cache folder rather than being selectable anywhere on the file system, plus the syncing mentioned above, but it's actually easier to maintain as the app's cache folder requires no user-acked permissions. ☝️
- Directory listing – this is my greatest concern here, the scripts processing pretty much depends on listing directories and its contents to filter specific files to inject, which would be pretty problematic in combination with HTTP. Even if you allow Dir listing on custom HTTP server, GitHub repo listing is another story with a different format – there's no unifying “API” here to support nicely.

To summarise things up, I'd pretty much prefer the app being KISS and delegate the folder syncing task to another client. As you noted, I personally use `git` for certain things in my HOME directories, Tampers folder included ✅ which allows me to be very flexible to even manage things to be present on all machines I use and having separate branches with machine-specific stuff – I use the same repo for multiple Mac and single Linux profiles – having `zsh` synced while keeping Tampers on Mac only is easily doable that way.

As an alternative – and I guess this would be very usable for people out there wishing to sync the same Tamper contents on all machines, as well as people tend to use same AdBlock rules consistently – I'd definitely go with simple Dropbox/Google Drive syncing here, it's pretty convenient, scalable to specific folders and works well with content pushing/syncing, probably way better than any side-implementation  in this app (which would additionally need very alternative approach to support both local and remote sources) would work. 😄
