### ISSUE TITLE
Scripts & styles are injected multiple times on many sites including YouTube, Google

### ISSUE THREAD

**Issue by TwirreM** [username0x0a/Tamperish#6]
Looking at the browser console, I sometimes see Tamperish's `[Tamperish] Injecting filename.ext ← youtube.com` being logged multiple times, as well as injected scripts' logs being duplicated. Sometimes hundreds of times, causing concern for resource usage.

I found a case where scripts were injected 211 times, a [specific question on StackOverflow](https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript), while other questions don't cause this behavior. An example of a site that does not cause this behavior is [example.com](http://example.com).

**Comment by howareyouo** [comment]
Same here, please fix !

**Comment by username0x0a** [comment]
Hey 👋 this is rather expected, especially with modern applications basically because of the fact that many modern web apps don't really reload fully for every action you perform, but rather just change their internal DOM & trigger some reloading (`onLoad`) routine repetitively, even multiple times when different stages of loading are performed (initial load → loading state with skeletons → fully rendered document), often followed by additional calls when loading more content or pages dynamically.

The only way how to give users a universal opportunity to react on all possible states it to stick with it & leave the responsibility to behave correctly on the actual script – that is, you should handle some expected state of injection (& perform some quick `guard`ed return) on your side; that is either by setting some `class=` flag on `html`/`body`/etc. element, checking for an existence of your injected elements by `id`/`class`es, etc.

Some webs (that behave statically f.e.) will require just a basic check or none at all, some (like YouTube f.e.) will require a more creative or complex solution, but there's really no single, universal way how to handle this for any website out in the wild.
